package com.isteer.enums;

public enum HrManagementEnum {

	Tenant_created_message(1111, "TENANT CREATED SUCCESSFULLY"),
	Tenant_creation_failed(9999,"TENANT CREATION FAILED"),
	Tenant_id_null(9067,"TENANT ID SHOULD BE PROVIDED"),
	No_list_of_tenansts(1121,"NO TENANT FOUND, PLEASE REGISTER TEANTS"),
	Tenant_updation_successfull(1232,"TENANT UPDATED SUCCESSFULLY"), 
	Tenant_valid_not_found(9321,"KINDLY PROVIDE THE VALID TENANT ID "),
	Tenant_deletion(1832, "REQUESTED TENANT HAVE BEEN DELETED SUCCESSFULLY"),
	TENANT_FAILED_DELETION(9023,"TENANT DELETION FAILED"),
	
     Department_created_message(1222,"DEPARTMENT CREATED SUCCESSFULLY"),
     Department_id_null(9822, "DEPARTMENT ID SHOULD BE PROVIDED"),
     DUPLICATE_KEY_EXCEPTION(9012,"ALREADY FOUND TRY ANOTHER"),
     DEPARTMENT_CREATION_FAILED(9888, "DEPARTMENT CREATION FAILED"),
     DEPARTMENT_UPDATION_SUCCESSFULL(1321, "DEPARTMENT UPDATED SUCCESSFULLY"),
     DEPARTMENT_VALID_NOT_FOUND(9082,"PROVIDED DEPARTMENT KEY IS NOT VAILD"),
     DEPARTMENT_DELETION(1238,"REQUESTED DEPARTMENT HAVE BEEN DELETED SUCCESSFULLY"),
     DEPARTMENT_DELETION_FAILED(9023,"DEPARTMENT DELETION FAILED"),

	USER_CREATED_SUCCESS(1231, "USER HAS BEEN CREATED SUCCESSFULLY"),
	Employee_id_null(9011,"EMPLOYEE ID SHOULD BE PROVIDED"),
	USER_FAILED_CREATION(9032,"USER REGISTERATION FAILED"),
	NO_USERS_FOUND_LIST(9021,"NO USERS FOUND"),
	USER_UPDATED_SUCCESS(1293,"USER DETAILS UPDATED SUCCESSFULLY"),
	USER_VALID_NOT_FOUND(9072,"PROVIDED EMPLOYEE KEY IS NOT VAILD"),
	EMPLOYEE_VALID_NOT_FOUND(9072,"PROVIDED EMPLOYEE KEY IS NOT VALID"),
	USER_UPDATE_FAIL(9073,"USER DETAILS CANNOT BE UPDATED"),
	User_deleted_success(1234,"USER HAVE BEEN DELETED SUCCESSFULLY"),
	User_deleted_fail(9033,"USER DELETION FAILED"),
	Role_added(1232,"ROLE ADDED SUCCESSFULLY"),
	Role_id_null(9822, "ROLE ID SHOULD BE PROVIDED"),
	Role_not_added(9033,"ROLE NOT ADDED SOEMTHING WENT WRONG"),
	USER_ROLE_UPDATED(1267,"USER ROLE HAS BEEN UPDATED SUCCESSFULLY"),
	USER_ROLE_UPDATION_FAIL(9857,"USER ROLE CANNOT BE UPDATED"),
	MissserveletException(1023,"REQUEST PARAMETER CANNOT BE EMPTY OR MISMATCHED"),
	Date_mismatch(1223,"PROVIDED INPUT FORMAT IS INCORRECT"),
	
	Leave_application_success(1093,"LEAVE REQUEST HAVE BEEN CREATED SUCCESSFULLY"),
	LEAVE_APPLICATION_FAILED(9021,"LEAVE APPLICATION FAILED"),
	LEAVE_APPROVAL_SUCCESS(1224,"LEAVE APPROVAL SUCCESS"),
	LEAVE_REJECTED_SUCCESS(1021, "LEAVE REJECTION SUCCESS"),
	LEAVE_REJECTION_FAILED(9023,"LEAVE REJECTION FAILED"),
	LEAVE_APPROVAL_FAILED(9323,"LEAVE APPROVAL FAILED , LEAVE ID MIGHT ALREADY APPROVED OR REJECTED"),
	LEAVE_REQUEST_NOT_FOUND(9823,"LEAVE REQUEST NOT FOUND "),
	
	END_POINT_CREATED(1312,"ENDPOINT ADDED SUCCESSFULLY "),
	END_POINT_FAILED(9278,"ENDPOINT CREATION FAILED"),
	METHOD_MAPPING_SUCCESS(1902,"HTTP METHOD ADDED SUCCESSFULLY"),
	METHOD_MAPPING_FAIL(9082,"OOPS!, HTTP METHOD NOT ADDED"),
	
	INTERNAL_SERVER_ERROR(9241, "An error occurred while accessing this end point."),
	EMPTY_DATA_EXCEPTION(9821, "NO SUCH DATA FOUND , RETRY WITH ANOTHER"),
	ILLEGAL_AGRUMENT(9021, "Role 'Employee' not found in the database."),
	Illegal_Argumnet_role(9236, "Role cannot found in the database"),
	Insertion_failed_Exception(9765, "OPERATION IN REPOSITORY FAILED"),
	AUTHORIZATION_DEINED(9022,"ACCESS DENIED FOR THIS END POINT !! "),
	TOKEN_EXPIRATION(9093, "TOKEN HAS BEEN EXPRIED"),
	INVALID_LEAVE_DATE(9021, "LEAVE DATE SHOULD NOT BE PAST "),
	LOGOUT_SUCCESS(1321,"YOU HAVE BEEN LOGGED OUT SUCCESSFULLY"),
	LOGOUT_FAILED(9643,"LOGOUT FAILED SOMETHING WENT WRONG"),
	Bad_credentials_exception(9218,"PROVIDED CREDENTIALS ARE WRONG, PROVIDE CORRECT USERNAME OR PASSWORD"),
	logout_invaild_token(9021, "Invalid Token , Token Already logged out");
	
	
	

	int statusCode;
	String statusMessage;

	public int getStatusCode() {
		return statusCode;
	}

	public void setStatusCode(int statusCode) {
		this.statusCode = statusCode;
	}

	public String getStatusMessage() {
		return statusMessage;
	}

	public void setStatusMessage(String statusMessage) {
		this.statusMessage = statusMessage;
	}
	
	private HrManagementEnum(int statusCode, String statusMessage) {
		this.statusCode = statusCode;
		this.statusMessage = statusMessage;
	}


}